[nginx]
YOUR_IP_HERE ansible_user=ec2-user letsencrypt_email=rbo06876@yuoia.com domain_name=turingboy.tk


[stat_server]
YOUR_IP_HERE ansible_user=ec2-user

[app_nodes]
YOUR_IP_HERE ansible_user=ec2-user
YOUR_IP_HERE ansible_user=ec2-user
YOUR_IP_HERE ansible_user=ec2-user
